<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>de84b104-3fa6-4ada-9fbe-d7e7e1a1c68f</elementGuidId>
    <imagePath></imagePath>
    <name>button_react_burger_menu_btn</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#react-burger-menu-btn</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'react-burger-menu-btn') and equals(@text,'Open Menu')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>react-burger-menu-btn</value>
        <webElementGuid>be549015-d073-4703-8ff5-1c4115b8469d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Open Menu</value>
        <webElementGuid>be549015-d073-4703-8ff5-1c4115b8469d</webElementGuid>
    </webElementProperties>
</WebElementEntity>