<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>db92b9a9-0a37-4969-b4a7-6ef0229ba12f</elementGuidId>
    <imagePath></imagePath>
    <name>button_react_burger_menu_btn</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#react-burger-menu-btn</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'react-burger-menu-btn') and equals(@text,'Open Menu')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>react-burger-menu-btn</value>
        <webElementGuid>aadf325c-6e68-4357-9bb0-0bfe37f4b7aa</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Open Menu</value>
        <webElementGuid>aadf325c-6e68-4357-9bb0-0bfe37f4b7aa</webElementGuid>
    </webElementProperties>
</WebElementEntity>